blog/apps/user/urls.py
from django.urls import path
from apps.user import views as views

app_name = "user"

urlpatterns = [
    path("user/profile", views.UserProfileView.as_view(), name="user_profile"),
    path("auth/register", views.RegisterView.as_view(), name="auth_register"),
    path("auth/login", views.LoginView.as_view(), name="auth_login"),
    path("auth/logout", views.LogoutView.as_view(), name="auth_logout"),

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('', include('apps.user.urls')),
    path('', include('apps.post.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/templates/components/ui/navbar.html
<nav>
    <div class="nav-actions">
        <div class="user-menu">
            <button class="login-btn">
                <i class="fas fa-user"></i>
                <span>Iniciar Sesión</span>
            </button>
            <div class="dropdown-menu">
                <div class="dropdown-divider"></div>
                
                {% if user.is_authenticated %}
                    <a href="{% url 'user:user_profile' %}" class="dropdown-item">Mi Perfil</a>
                    <a href="{% url 'user:auth_logout' %}" class="dropdown-item">Cerrar Sesión</a>
                    <a href="#" class="dropdown-item">Mis Favoritos</a>
                    <a href="#" class="dropdown-item">Mis Publicaciones</a>

                {% else %}
                    <a href="{% url 'user:auth_register' %}" class="dropdown-item">Registrarse</a>
                    <a href="{% url 'user:auth_login' %}" class="dropdown-item">Iniciar sesión</a>
                    
                {% endif %}
                    
            </div>
        </div>
    </div>
</nav>